#!/usr/bin/env bash
# SessionStart hook — provisions a Docker-free dev stack for Claude Code web
# sessions, then injects the superpowers using-superpowers skill as context.
set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel)}"
SKILLS_DIR="${PROJECT_DIR}/.claude/skills"
DEVSTACK_LOG="/tmp/session-start-devstack.log"

# docker compose (site + MariaDB via Apache/php:8.1-apache) is how this repo
# normally does local dev, but Claude Code web sessions have no Docker
# daemon. When that's the case, stand up an equivalent stack natively:
# MariaDB directly, app/config.php pointing at it, and PHP's built-in
# server as a stand-in for the Apache container. Idempotent and best-effort —
# never fails session startup.
setup_dev_stack() {
  if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
    return 0
  fi
  if docker info >/dev/null 2>&1; then
    return 0
  fi

  if ! command -v mariadbd >/dev/null 2>&1 && ! command -v mysqld >/dev/null 2>&1; then
    DEBIAN_FRONTEND=noninteractive sudo apt-get update -y
    DEBIAN_FRONTEND=noninteractive sudo apt-get install -y mariadb-server
  fi

  if ! sudo mysqladmin ping >/dev/null 2>&1; then
    sudo mkdir -p /run/mysqld
    sudo chown mysql:mysql /run/mysqld
    sudo -u mysql /usr/sbin/mariadbd --datadir=/var/lib/mysql \
      --skip-networking=0 --bind-address=127.0.0.1 \
      >/tmp/mariadbd.log 2>&1 &
    disown
    for _ in $(seq 1 30); do
      sudo mysqladmin ping >/dev/null 2>&1 && break
      sleep 1
    done
  fi

  sudo mysql -e "
    CREATE DATABASE IF NOT EXISTS lescanetons CHARACTER SET utf8mb4;
    CREATE DATABASE IF NOT EXISTS lescanetons_test CHARACTER SET utf8mb4;
    CREATE USER IF NOT EXISTS 'canetons'@'127.0.0.1' IDENTIFIED BY 'canetons';
    CREATE USER IF NOT EXISTS 'canetons'@'localhost' IDENTIFIED BY 'canetons';
    GRANT ALL PRIVILEGES ON lescanetons.* TO 'canetons'@'127.0.0.1';
    GRANT ALL PRIVILEGES ON lescanetons.* TO 'canetons'@'localhost';
    GRANT ALL PRIVILEGES ON lescanetons_test.* TO 'canetons'@'127.0.0.1';
    GRANT ALL PRIVILEGES ON lescanetons_test.* TO 'canetons'@'localhost';
    FLUSH PRIVILEGES;
  "

  for db in lescanetons lescanetons_test; do
    table_count=$(sudo mysql -N -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${db}';")
    if [ "${table_count:-0}" -eq 0 ]; then
      sudo mysql "$db" < "$PROJECT_DIR/docker/db/init/01-schema.sql"
      sudo mysql "$db" < "$PROJECT_DIR/docker/db/init/02-seed.sql"
    fi
  done

  if [ ! -f "$PROJECT_DIR/app/config.php" ]; then
    cat > "$PROJECT_DIR/app/config.php" <<'PHP'
<?php
// Web-session dev config, generated by .claude/hooks/session-start.sh.
// Mirrors config/config.docker.php but points at the native MariaDB
// instance the hook provisions (no Docker daemon in Claude Code web sessions).
return [
    'db' => [
        'host' => '127.0.0.1',
        'user' => 'canetons',
        'pass' => 'canetons',
        'name' => 'lescanetons',
        'charset' => 'utf8mb4',
    ],
];
PHP
  fi

  if ! pgrep -f "php -S 127.0.0.1:8090" >/dev/null 2>&1; then
    (cd "$PROJECT_DIR/app" && nohup php -S 127.0.0.1:8090 >/tmp/php-dev-server.log 2>&1 &)
  fi

  if [ ! -d "$PROJECT_DIR/vendor" ]; then
    (cd "$PROJECT_DIR" && composer install --no-interaction)
  fi
}

setup_dev_stack >"$DEVSTACK_LOG" 2>&1 || true

using_superpowers_content=$(cat "${SKILLS_DIR}/using-superpowers/SKILL.md" 2>&1 || echo "Error reading using-superpowers skill")

escape_for_json() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    s="${s//$'\n'/\\n}"
    s="${s//$'\r'/\\r}"
    s="${s//$'\t'/\\t}"
    printf '%s' "$s"
}

escaped=$(escape_for_json "$using_superpowers_content")
context="<EXTREMELY_IMPORTANT>\nYou have superpowers.\n\n**Below is the full content of your 'superpowers:using-superpowers' skill - your introduction to using skills. For all other skills, use the 'Skill' tool:**\n\n${escaped}\n</EXTREMELY_IMPORTANT>"

printf '{\n  "hookSpecificOutput": {\n    "hookEventName": "SessionStart",\n    "additionalContext": "%s"\n  }\n}\n' "$context"
