import js from '@eslint/js';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default [
  js.configs.recommended,
  {
    files: ['app/assets/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.browser },
    },
    rules: {
      // Several files use a leading-underscore parameter name as an explicit
      // "intentionally unused" placeholder (e.g. `.then((_) => ...)`), which
      // is a common, readable convention rather than a bug.
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
  {
    // node:test files co-located with the browser modules they cover (e.g.
    // app/assets/js/api.test.mjs), run by `npm run test:js`. They execute in
    // Node but stub the browser APIs the module under test uses, so they need
    // both sets of globals — the block above supplies only browser ones, and
    // only to *.js. The .mjs extension is deliberate: vite.config.js builds an
    // entry per *.js file in that directory, so a test named *.test.js would be
    // bundled as if it were page code.
    files: ['app/assets/js/**/*.test.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node },
    },
  },
  {
    // The SPA. Typed with typescript-eslint's parser but WITHOUT type-aware
    // linting: the type-checked rule set needs a program per run and doubles
    // lint time, and `npm run check` already runs `tsc --noEmit` over the same
    // files, so the types are enforced either way.
    files: ['web/**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.browser },
      parser: tseslint.parser,
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      'react-hooks': reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // The base rule does not understand type-only syntax (it flags a type
      // parameter or an `import type` as unused); the TS-aware one replaces it.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      // no-undef cannot see TypeScript's lib types — it reports DOM types like
      // RequestInit as undefined globals. TypeScript itself reports genuinely
      // undefined identifiers, and `npm run check` runs tsc over these files,
      // so the rule is redundant here as well as wrong.
      'no-undef': 'off',
    },
  },
  {
    // Generated by orval from api/openapi.json — never hand-edited, so linting
    // it only ever produces noise no one may act on. See orval.config.ts.
    ignores: ['web/src/api/generated/**'],
  },
];
