import { fileURLToPath } from "node:url";

import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

/**
 * The SPA build.
 *
 * `root: 'web'` makes web/index.html the entry. `base: '/'` because the shell is
 * served from the document root, unlike the old per-page bundles which were
 * served from /assets/dist/.
 *
 * outDir is dist/build/ — the deploy artifact — because tools/build.mjs copies
 * the Laravel API in beside this output afterwards. dist/build/ is git-ignored
 * and fully regenerated by whichever build ran last, and tools/build.mjs starts
 * by removing it, so the two builds cannot corrupt each other.
 *
 * The dev server proxies /api and /sanctum to the `web` container, so the
 * browser sees ONE origin on :5173. That is not a convenience — Sanctum's
 * stateful SPA flow authenticates by cookie, and a cross-origin dev setup would
 * need CORS plus SameSite handling that production does not have, i.e. it would
 * stop testing the real thing. The dev origin is listed in
 * SANCTUM_STATEFUL_DOMAINS in docker/api/env.docker only, never in a shipped
 * default.
 *
 * changeOrigin stays false: Sanctum matches the request's Host against
 * SANCTUM_STATEFUL_DOMAINS, so rewriting it to the target would defeat the
 * entry we just added for :5173.
 */
/**
 * Where the dev server forwards /api and /sanctum.
 *
 * Defaults to the published port, which is right when `npm run dev:web` runs on
 * the host. Inside the compose stack the dev server runs in the `assets`
 * container, where localhost is that container and not the site — so
 * docker-compose.yml sets this to the `web` service by name. Without it the
 * proxy answers 502 for every API call and the SPA looks broken with no clue
 * why.
 */
const apiProxyTarget = process.env.VITE_API_PROXY_TARGET ?? "http://localhost:8090";

export default defineConfig({
  root: "web",
  base: "/",
  plugins: [react(), tailwindcss()],
  // `@/` -> web/src. Note root is "web" below, so this is resolved from the
  // REPO root and not from the Vite root. It must agree with tsconfig.json's
  // paths and with vitest.config.ts, which is a separate config file in this
  // project -- see its own comment.
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./web/src", import.meta.url)),
    },
  },
  build: {
    outDir: "../dist/build",
    emptyOutDir: true,
    sourcemap: false,
  },
  server: {
    // PORT, when something upstream assigns one.
    //
    // Vite does not read PORT on its own: left alone it takes 5173, which the
    // compose `assets` container already publishes. That is fine for the main
    // checkout and wrong in a git worktree, where :5173 serves the OTHER tree's
    // web/ and a preview shows code that is not the code you are editing.
    // Honouring PORT is what lets each worktree run a dev server of its own on
    // whatever port is free.
    //
    // strictPort only when PORT was assigned: a caller that named a port needs
    // the server on THAT port or nowhere, because it is about to open it.
    // Vite's own default behaviour — drift to the next free port — is right
    // when nobody asked for one.
    //
    // The Playwright harness passes `--port 5174 --strictPort` on the command
    // line instead, which outranks this; see playwright.config.ts for why it
    // owns a port of its own.
    port: process.env.PORT ? Number(process.env.PORT) : undefined,
    strictPort: process.env.PORT !== undefined,
    proxy: {
      "/api": { target: apiProxyTarget, changeOrigin: false },
      "/sanctum": { target: apiProxyTarget, changeOrigin: false },
    },
    // Filesystem events do not cross a Docker Desktop bind mount reliably on
    // Windows or macOS, so the dev server inside the `assets` container simply
    // never notices an edit — the page keeps serving the previous version and
    // the only fix looks like "restart the container", which nobody guesses.
    // Polling is the standard workaround; it costs CPU, so it is opt-in and
    // docker-compose.yml turns it on for that container alone.
    watch: process.env.VITE_USE_POLLING === "1" ? { usePolling: true, interval: 300 } : undefined,
  },
});
