import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

/**
 * The SPA build.
 *
 * `root: 'web'` makes web/index.html the entry. `base: '/'` because the shell is
 * served from the document root, unlike the old per-page bundles which were
 * served from /assets/dist/.
 *
 * outDir is dist/build/ — the deploy artifact — because tools/build.mjs copies
 * the Laravel API in beside this output afterwards. dist/build/ is git-ignored
 * and fully regenerated by whichever build ran last, and tools/build.mjs starts
 * by removing it, so the two builds cannot corrupt each other.
 *
 * Vite resolves vite.config.js BEFORE vite.config.ts, so while app/'s config
 * still exists every Vite invocation in package.json passes --config
 * explicitly. The cutover deletes vite.config.js and the flags go with it.
 */
export default defineConfig({
  root: "web",
  base: "/",
  plugins: [react(), tailwindcss()],
  build: {
    outDir: "../dist/build",
    emptyOutDir: true,
    sourcemap: false,
  },
});
