import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

/**
 * The SPA build.
 *
 * `root: 'web'` makes web/index.html the entry. `base: '/'` because the shell is
 * served from the document root, unlike the old per-page bundles which were
 * served from /assets/dist/.
 *
 * outDir is dist/build/ — the deploy artifact — because tools/build.mjs copies
 * the Laravel API in beside this output afterwards. dist/build/ is git-ignored
 * and fully regenerated by whichever build ran last, and tools/build.mjs starts
 * by removing it, so the two builds cannot corrupt each other.
 *
 * The dev server proxies /api and /sanctum to the `web` container, so the
 * browser sees ONE origin on :5173. That is not a convenience — Sanctum's
 * stateful SPA flow authenticates by cookie, and a cross-origin dev setup would
 * need CORS plus SameSite handling that production does not have, i.e. it would
 * stop testing the real thing. The dev origin is listed in
 * SANCTUM_STATEFUL_DOMAINS in docker/api/env.docker only, never in a shipped
 * default.
 *
 * changeOrigin stays false: Sanctum matches the request's Host against
 * SANCTUM_STATEFUL_DOMAINS, so rewriting it to the target would defeat the
 * entry we just added for :5173.
 */
export default defineConfig({
  root: "web",
  base: "/",
  plugins: [react(), tailwindcss()],
  build: {
    outDir: "../dist/build",
    emptyOutDir: true,
    sourcemap: false,
  },
  server: {
    proxy: {
      "/api": { target: "http://localhost:8090", changeOrigin: false },
      "/sanctum": { target: "http://localhost:8090", changeOrigin: false },
    },
  },
});
