#!/usr/bin/env bash
# On-demand dev-stack provisioner for Claude Code web sessions.
#
# docker compose (site + MariaDB via Apache/php:8.1-apache) is how this repo
# normally does local dev, but Claude Code web sessions have no Docker daemon.
# When that's the case, this stands up an equivalent stack natively: MariaDB
# directly, both databases seeded, and code/config.php pointing at it.
#
# Invoked on-demand by the DB-dependent npm scripts (via ensure-dev-stack.mjs),
# NOT from the SessionStart hook — session startup must stay fast and must not
# block on apt/DB provisioning. Idempotent and best-effort: safe to run
# repeatedly; a no-op when Docker is reachable or outside a web session.
set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel)}"

# Only meaningful on a Docker-less Claude Code web session. Local Docker dev
# and CI provision the DB via docker compose / service containers instead.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi
if docker info >/dev/null 2>&1; then
  exit 0
fi

if ! command -v mariadbd >/dev/null 2>&1 && ! command -v mysqld >/dev/null 2>&1; then
  # `|| true`: some web-session images ship extra PPA sources (e.g. deadsnakes,
  # ondrej/php) unrelated to this script that may be unreachable under the
  # session's egress policy. apt-get update fails non-zero on ANY repo error
  # even when the repos we actually need (Ubuntu main/universe/security)
  # succeeded, so a hard failure here would abort provisioning over a package
  # source we never use. The subsequent install still fails loudly if
  # mariadb-server itself is genuinely unavailable.
  DEBIAN_FRONTEND=noninteractive sudo apt-get update -y || true
  DEBIAN_FRONTEND=noninteractive sudo apt-get install -y mariadb-server
fi

if ! sudo mysqladmin ping >/dev/null 2>&1; then
  sudo mkdir -p /run/mysqld
  sudo chown mysql:mysql /run/mysqld
  sudo -u mysql /usr/sbin/mariadbd --datadir=/var/lib/mysql \
    --skip-networking=0 --bind-address=127.0.0.1 \
    >/tmp/mariadbd.log 2>&1 &
  disown
  for _ in $(seq 1 30); do
    sudo mysqladmin ping >/dev/null 2>&1 && break
    sleep 1
  done
fi

sudo mysql -e "
  CREATE DATABASE IF NOT EXISTS lescanetons CHARACTER SET utf8mb4;
  CREATE DATABASE IF NOT EXISTS lescanetons_test CHARACTER SET utf8mb4;
  CREATE USER IF NOT EXISTS 'canetons'@'127.0.0.1' IDENTIFIED BY 'canetons';
  CREATE USER IF NOT EXISTS 'canetons'@'localhost' IDENTIFIED BY 'canetons';
  GRANT ALL PRIVILEGES ON lescanetons.* TO 'canetons'@'127.0.0.1';
  GRANT ALL PRIVILEGES ON lescanetons.* TO 'canetons'@'localhost';
  GRANT ALL PRIVILEGES ON lescanetons_test.* TO 'canetons'@'127.0.0.1';
  GRANT ALL PRIVILEGES ON lescanetons_test.* TO 'canetons'@'localhost';
  FLUSH PRIVILEGES;
"

for db in lescanetons lescanetons_test; do
  table_count=$(sudo mysql -N -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${db}';")
  if [ "${table_count:-0}" -eq 0 ]; then
    sudo mysql "$db" < "$PROJECT_DIR/docker/db/init/01-schema.sql"
    sudo mysql "$db" < "$PROJECT_DIR/docker/db/init/02-seed.sql"
  fi
done

if [ ! -f "$PROJECT_DIR/code/config.php" ]; then
  cat > "$PROJECT_DIR/code/config.php" <<'PHP'
<?php
// Web-session dev config, generated by tools/ensure-dev-stack.sh.
// Mirrors config/config.docker.php but points at the native MariaDB
// instance provisioned on-demand (no Docker daemon in Claude Code web sessions).
return [
    'db' => [
        'host' => '127.0.0.1',
        'user' => 'canetons',
        'pass' => 'canetons',
        'name' => 'lescanetons',
        'charset' => 'utf8mb4',
    ],
];
PHP
fi
