<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Creating a person on the roster — which means creating an account, because
 * every member has one (2026_09_08_000001).
 *
 * `username` is REQUIRED for that reason. It used to be optional, back when a
 * row could be a person without a login; that model is what let somebody hold
 * members.manage while being unable to authenticate, and deleting the only real
 * administrator then locked the band out.
 *
 * There is deliberately no `roleIds` field either: granting a permission is
 * exactly one operation, PUT /members/{member}/roles, which re-authenticates
 * and checks the lockout invariants. Accepting roles here would let a stolen
 * session create a working administrator without ever proving who it is.
 *
 * There is deliberately no `password` field. The password is GENERATED by the
 * controller and returned once — an administrator reads it down the phone (§4.4)
 * — so nobody types a credential into this form and no weak one can be chosen.
 *
 * Field names are camelCase, matching what the SPA sends and what
 * App\Exceptions\ApiError echoes into fields[].field, where web/src/i18n/fr.ts
 * looks them up. Renaming one silently breaks its French error message.
 *
 * RULE ORDER IS LOAD-BEARING: ApiError reports only the FIRST failed rule per
 * field, so `required` comes first (an empty field reports `required`, not
 * `invalid_format`) and `max` precedes `unique` (an over-long username reports
 * `too_long` rather than costing a database round-trip).
 */
class StoreMemberRequest extends FormRequest
{
    /** @return array<string, array<int, mixed>> */
    public function rules(): array
    {
        return [
            'firstName' => ['required', 'string', 'max:255'],
            'lastName' => ['required', 'string', 'max:255'],

            // Lower case, digits, dot, hyphen, underscore. The seeded logins
            // look like `demo.direction`, and a username that has to be
            // dictated should not depend on capitalisation. The column collates
            // case-insensitively anyway, so `Lea` and `lea` would be the same
            // account — the rule makes that visible rather than surprising.
            'username' => ['required', 'string', 'max:255', 'regex:/^[a-z0-9._-]+$/', 'unique:members,username'],

            'sectionId' => ['nullable', 'integer', 'exists:sections,id'],
            'committeeTitle' => ['nullable', 'string', 'max:255'],
            'instructorOfSectionId' => ['nullable', 'integer', 'exists:sections,id'],

            // Required, not defaulted: publication of a minor's name is a
            // decision somebody makes, so the form has to state it rather than
            // inherit it.
            'publicVisible' => ['required', 'boolean'],
        ];
    }
}
